# Generated by Django 3.2.8 on 2021-12-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=100)),
                ('quantity', models.FloatField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
