# Generated by Django 3.2.8 on 2022-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20220110_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='coin_balance',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='is_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bot',
            name='market',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='volume',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
