# Generated by Django 3.2.8 on 2022-01-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20220110_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredMarket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coin_list', models.JSONField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
