# Generated by Django 3.2.8 on 2022-01-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_filteredmarket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteredmarket',
            name='coin_list',
        ),
        migrations.AddField(
            model_name='filteredmarket',
            name='coin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filteredmarket',
            name='volume',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
