# Generated by Django 3.2.8 on 2022-01-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20220110_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filteredmarket',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='filteredmarket',
            name='created_at',
        ),
    ]
