# Generated by Django 3.2.8 on 2022-01-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20220110_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filteredmarket',
            options={},
        ),
        migrations.AlterField(
            model_name='filteredmarket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
