# Generated by Django 3.2.8 on 2022-01-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_bot_coin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bid_price',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
