# Generated by Django 3.2.8 on 2022-01-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_bot_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='market',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
