# Generated by Django 3.2.8 on 2022-01-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_transactionhistory_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='uuid',
            field=models.TextField(),
        ),
    ]
