# Generated by Django 3.2.8 on 2022-01-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_transactionhistory_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
