# Generated by Django 3.2.8 on 2022-01-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_bot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
