# Generated by Django 3.2.8 on 2022-01-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_bot_is_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='loss_percent',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='profit_percent',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
